### ISSUE TITLE
Did you run MNN as gpu mode or cpu mode?

### ISSUE THREAD

**Issue by twmht** [Qengineering/LFFD-MNN-Jetson-Nano#1]
Hi,

Did you run MNN as gpu mode or cpu mode in Raspberry Pi 4?

By the way, is FPS including bounding box regression and nms?

**Comment by Qengineering** [comment]
MNN runs in GPU (CUDA) mode if installed on a Jetson Nano.
Because the Raspberry Pi hasn't CUDA acceleration, the installation of MNN on the RPi 4 is CPU.

The FPS shown is only the inference time of the network divide by the elapsed time. No image fetching and (OpenCV) drawing is included in the number.
